INSERT INTO DRUG(DRG_ID,DRG_NAME,DRG_TYPE,DRG_COMP_ID,DRG_SELLING_PRC,DRG_BUYING_PRC,DRG_GOV_SUPPORT,DRG_EXPIRE)
VALUES(1, 'Parol', 'Analgesic',35,10,8,0.7,TO_DATE(05-APR-2024));

INSERT INTO DRUG(DRG_ID,DRG_NAME,DRG_TYPE,DRG_COMP_ID,DRG_SELLING_PRC,DRG_BUYING_PRC,DRG_GOV_SUPPORT,DRG_EXPIRE)
VALUES(2, 'Arveles', 'Anti-inflammatory',36,12,10,0.7,TO_DATE(22-MAY-2020));

INSERT INTO DRUG(DRG_ID,DRG_NAME,DRG_TYPE,DRG_COMP_ID,DRG_SELLING_PRC,DRG_BUYING_PRC,DRG_GOV_SUPPORT,DRG_EXPIRE)
VALUES(3, 'Parafon', 'Muscle Relaxing Agent',37,11,8,0.6,TO_DATE(08-AUG-2020));

INSERT INTO DRUG(DRG_ID,DRG_NAME,DRG_TYPE,DRG_COMP_ID,DRG_SELLING_PRC,DRG_BUYING_PRC,DRG_GOV_SUPPORT,DRG_EXPIRE)
VALUES(4, 'Nurofen', 'Anti-inflammatory',38,9,6,0.7,TO_DATE(30-NOV-2021));

INSERT INTO DRUG(DRG_ID,DRG_NAME,DRG_TYPE,DRG_COMP_ID,DRG_SELLING_PRC,DRG_BUYING_PRC,DRG_GOV_SUPPORT,DRG_EXPIRE)
VALUES(5, 'Vermidon', 'Analgesic',39,10,9,0.7,TO_DATE(24-OCT-2022));

INSERT INTO DRUG(DRG_ID,DRG_NAME,DRG_TYPE,DRG_COMP_ID,DRG_SELLING_PRC,DRG_BUYING_PRC,DRG_GOV_SUPPORT,DRG_EXPIRE)
VALUES(6, 'Fenistil', 'Anti-histaminic',40,15,12,0.4,TO_DATE(24-FEB-2022));

INSERT INTO DRUG(DRG_ID,DRG_NAME,DRG_TYPE,DRG_COMP_ID,DRG_SELLING_PRC,DRG_BUYING_PRC,DRG_GOV_SUPPORT,DRG_EXPIRE)
VALUES(6, 'Concerta', 'CNS Stimulant',41,250,180,0.2,TO_DATE(25-FEB-2026));