
-- 2 Pharmacies
INSERT INTO PHARMACY VALUES(1, 'Sifa', 'Unlu Sk. No.6', '2322547685');
INSERT INTO PHARMACY VALUES(2, 'Hayat', 'Mithatpasa Cd. No.279','2323553535');

-- 3 Inventories
-- Two of them is connected to the first pharmacy
-- and the last one is connected to the second pharmacy
INSERT INTO INVENTORY VALUES(1, 1);
INSERT INTO INVENTORY VALUES(2, 1);
INSERT INTO INVENTORY VALUES(3, 2);

-- 15 Incomes
INSERT INTO INCOME(in_id, in_date, ph_id) VALUES (1, TO_DATE('05-APR-2019', 'DD-MON-YYYY'), 2);
INSERT INTO INCOME(in_id, in_date, ph_id) VALUES (2, TO_DATE('30-MAY-2019', 'DD-MON-YYYY'), 2);
INSERT INTO INCOME(in_id, in_date, ph_id) VALUES (3, TO_DATE('09-JAN-2019', 'DD-MON-YYYY'), 2);
INSERT INTO INCOME(in_id, in_date, ph_id) VALUES (4, TO_DATE('12-JAN-2019', 'DD-MON-YYYY'), 2);
INSERT INTO INCOME(in_id, in_date, ph_id) VALUES (5, TO_DATE('23-APR-2019', 'DD-MON-YYYY'), 2);
INSERT INTO INCOME(in_id, in_date, ph_id) VALUES (6, TO_DATE('10-APR-2019', 'DD-MON-YYYY'), 1);
INSERT INTO INCOME(in_id, in_date, ph_id) VALUES (7, TO_DATE('23-APR-2019', 'DD-MON-YYYY'), 1);
INSERT INTO INCOME(in_id, in_date, ph_id) VALUES (8, TO_DATE('19-MAY-2019', 'DD-MON-YYYY'), 1);
INSERT INTO INCOME(in_id, in_date, ph_id) VALUES (9, TO_DATE('19-MAY-2019', 'DD-MON-YYYY'), 1);
INSERT INTO INCOME(in_id, in_date, ph_id) VALUES (10, TO_DATE('29-OCT-2019', 'DD-MON-YYYY'), 1);
INSERT INTO INCOME(in_id, in_date, ph_id) VALUES (11, TO_DATE('12-DEC-2019', 'DD-MON-YYYY'), 1);
INSERT INTO INCOME(in_id, in_date, ph_id) VALUES (12, TO_DATE('06-SEP-2019', 'DD-MON-YYYY'), 1);
INSERT INTO INCOME(in_id, in_date, ph_id) VALUES (13, TO_DATE('02-NOV-2019', 'DD-MON-YYYY'), 1);
INSERT INTO INCOME(in_id, in_date, ph_id) VALUES (14, TO_DATE('06-NOV-2019', 'DD-MON-YYYY'), 1);
INSERT INTO INCOME(in_id, in_date, ph_id) VALUES (15, TO_DATE('13-DEC-2019', 'DD-MON-YYYY'), 1);

-- 50 Outcomes
INSERT INTO OUTCOME(OUT_ID, OUT_DATE, PH_ID) VALUES (1, TO_DATE('13-DEC-2019', 'DD-MON-YYYY'), 1);
INSERT INTO OUTCOME(OUT_ID, OUT_DATE, PH_ID) VALUES (2, TO_DATE('10-DEC-2019', 'DD-MON-YYYY'), 1);
INSERT INTO OUTCOME(OUT_ID, OUT_DATE, PH_ID) VALUES (3, TO_DATE('01-DEC-2019', 'DD-MON-YYYY'), 1);
INSERT INTO OUTCOME(OUT_ID, OUT_DATE, PH_ID) VALUES (4, TO_DATE('05-DEC-2019', 'DD-MON-YYYY'), 1);
INSERT INTO OUTCOME(OUT_ID, OUT_DATE, PH_ID) VALUES (5, TO_DATE('30-DEC-2019', 'DD-MON-YYYY'), 1);
INSERT INTO OUTCOME(OUT_ID, OUT_DATE, PH_ID) VALUES (6, TO_DATE('03-NOV-2019', 'DD-MON-YYYY'), 1);
INSERT INTO OUTCOME(OUT_ID, OUT_DATE, PH_ID) VALUES (7, TO_DATE('11-NOV-2019', 'DD-MON-YYYY'), 1);
INSERT INTO OUTCOME(OUT_ID, OUT_DATE, PH_ID) VALUES (8, TO_DATE('24-NOV-2019', 'DD-MON-YYYY'), 1);
INSERT INTO OUTCOME(OUT_ID, OUT_DATE, PH_ID) VALUES (9, TO_DATE('30-NOV-2019', 'DD-MON-YYYY'), 1);
INSERT INTO OUTCOME(OUT_ID, OUT_DATE, PH_ID) VALUES (10, TO_DATE('30-NOV-2019', 'DD-MON-YYYY'), 1);
INSERT INTO OUTCOME(OUT_ID, OUT_DATE, PH_ID) VALUES (11, TO_DATE('03-OCT-2019', 'DD-MON-YYYY'), 1);
INSERT INTO OUTCOME(OUT_ID, OUT_DATE, PH_ID) VALUES (12, TO_DATE('08-OCT-2019', 'DD-MON-YYYY'), 1);
INSERT INTO OUTCOME(OUT_ID, OUT_DATE, PH_ID) VALUES (13, TO_DATE('12-OCT-2019', 'DD-MON-YYYY'), 1);
INSERT INTO OUTCOME(OUT_ID, OUT_DATE, PH_ID) VALUES (14, TO_DATE('12-OCT-2019', 'DD-MON-YYYY'), 1);
INSERT INTO OUTCOME(OUT_ID, OUT_DATE, PH_ID) VALUES (15, TO_DATE('13-OCT-2019', 'DD-MON-YYYY'), 1);
INSERT INTO OUTCOME(OUT_ID, OUT_DATE, PH_ID) VALUES (16, TO_DATE('18-OCT-2019', 'DD-MON-YYYY'), 1);
INSERT INTO OUTCOME(OUT_ID, OUT_DATE, PH_ID) VALUES (17, TO_DATE('21-OCT-2019', 'DD-MON-YYYY'), 1);
INSERT INTO OUTCOME(OUT_ID, OUT_DATE, PH_ID) VALUES (18, TO_DATE('24-OCT-2019', 'DD-MON-YYYY'), 2);
INSERT INTO OUTCOME(OUT_ID, OUT_DATE, PH_ID) VALUES (19, TO_DATE('25-OCT-2019', 'DD-MON-YYYY'), 2);
INSERT INTO OUTCOME(OUT_ID, OUT_DATE, PH_ID) VALUES (20, TO_DATE('08-SEP-2019', 'DD-MON-YYYY'), 2);
INSERT INTO OUTCOME(OUT_ID, OUT_DATE, PH_ID) VALUES (21, TO_DATE('15-SEP-2019', 'DD-MON-YYYY'), 2);
INSERT INTO OUTCOME(OUT_ID, OUT_DATE, PH_ID) VALUES (22, TO_DATE('20-SEP-2019', 'DD-MON-YYYY'), 2);
INSERT INTO OUTCOME(OUT_ID, OUT_DATE, PH_ID) VALUES (23, TO_DATE('22-SEP-2019', 'DD-MON-YYYY'), 2);
INSERT INTO OUTCOME(OUT_ID, OUT_DATE, PH_ID) VALUES (24, TO_DATE('27-SEP-2019', 'DD-MON-YYYY'), 2);
INSERT INTO OUTCOME(OUT_ID, OUT_DATE, PH_ID) VALUES (25, TO_DATE('03-JUN-2019', 'DD-MON-YYYY'), 2);
INSERT INTO OUTCOME(OUT_ID, OUT_DATE, PH_ID) VALUES (26, TO_DATE('18-JUN-2019', 'DD-MON-YYYY'), 2);
INSERT INTO OUTCOME(OUT_ID, OUT_DATE, PH_ID) VALUES (27, TO_DATE('20-JUN-2019', 'DD-MON-YYYY'), 2);
INSERT INTO OUTCOME(OUT_ID, OUT_DATE, PH_ID) VALUES (28, TO_DATE('20-JUN-2019', 'DD-MON-YYYY'), 2);
INSERT INTO OUTCOME(OUT_ID, OUT_DATE, PH_ID) VALUES (29, TO_DATE('25-JUN-2019', 'DD-MON-YYYY'), 2);
INSERT INTO OUTCOME(OUT_ID, OUT_DATE, PH_ID) VALUES (30, TO_DATE('10-MAY-2019', 'DD-MON-YYYY'), 2);
INSERT INTO OUTCOME(OUT_ID, OUT_DATE, PH_ID) VALUES (31, TO_DATE('13-MAY-2019', 'DD-MON-YYYY'), 2);
INSERT INTO OUTCOME(OUT_ID, OUT_DATE, PH_ID) VALUES (32, TO_DATE('15-MAY-2019', 'DD-MON-YYYY'), 2);
INSERT INTO OUTCOME(OUT_ID, OUT_DATE, PH_ID) VALUES (33, TO_DATE('20-MAY-2019', 'DD-MON-YYYY'), 2);
INSERT INTO OUTCOME(OUT_ID, OUT_DATE, PH_ID) VALUES (34, TO_DATE('12-APR-2019', 'DD-MON-YYYY'), 2);
INSERT INTO OUTCOME(OUT_ID, OUT_DATE, PH_ID) VALUES (35, TO_DATE('13-APR-2019', 'DD-MON-YYYY'), 2);
INSERT INTO OUTCOME(OUT_ID, OUT_DATE, PH_ID) VALUES (36, TO_DATE('19-APR-2019', 'DD-MON-YYYY'), 2);
INSERT INTO OUTCOME(OUT_ID, OUT_DATE, PH_ID) VALUES (37, TO_DATE('20-APR-2019', 'DD-MON-YYYY'), 2);
INSERT INTO OUTCOME(OUT_ID, OUT_DATE, PH_ID) VALUES (38, TO_DATE('23-APR-2019', 'DD-MON-YYYY'), 2);
INSERT INTO OUTCOME(OUT_ID, OUT_DATE, PH_ID) VALUES (39, TO_DATE('05-FEB-2019', 'DD-MON-YYYY'), 2);
INSERT INTO OUTCOME(OUT_ID, OUT_DATE, PH_ID) VALUES (40, TO_DATE('09-FEB-2019', 'DD-MON-YYYY'), 2);
INSERT INTO OUTCOME(OUT_ID, OUT_DATE, PH_ID) VALUES (41, TO_DATE('16-FEB-2019', 'DD-MON-YYYY'), 2);
INSERT INTO OUTCOME(OUT_ID, OUT_DATE, PH_ID) VALUES (42, TO_DATE('24-FEB-2019', 'DD-MON-YYYY'), 2);
INSERT INTO OUTCOME(OUT_ID, OUT_DATE, PH_ID) VALUES (43, TO_DATE('16-JAN-2019', 'DD-MON-YYYY'), 2);
INSERT INTO OUTCOME(OUT_ID, OUT_DATE, PH_ID) VALUES (44, TO_DATE('16-JAN-2019', 'DD-MON-YYYY'), 2);
INSERT INTO OUTCOME(OUT_ID, OUT_DATE, PH_ID) VALUES (45, TO_DATE('20-JAN-2019', 'DD-MON-YYYY'), 2);
INSERT INTO OUTCOME(OUT_ID, OUT_DATE, PH_ID) VALUES (46, TO_DATE('22-JAN-2019', 'DD-MON-YYYY'), 2);
INSERT INTO OUTCOME(OUT_ID, OUT_DATE, PH_ID) VALUES (47, TO_DATE('23-JAN-2019', 'DD-MON-YYYY'), 2);
INSERT INTO OUTCOME(OUT_ID, OUT_DATE, PH_ID) VALUES (48, TO_DATE('25-JAN-2019', 'DD-MON-YYYY'), 2);
INSERT INTO OUTCOME(OUT_ID, OUT_DATE, PH_ID) VALUES (49, TO_DATE('26-JAN-2019', 'DD-MON-YYYY'), 2);
INSERT INTO OUTCOME(OUT_ID, OUT_DATE, PH_ID) VALUES (50, TO_DATE('29-JAN-2019', 'DD-MON-YYYY'), 2);