ALTER TABLE INVENTORY DROP CONSTRAINT INV_FK;
ALTER TABLE SUPPLIERS DROP CONSTRAINT SUPP_FK_1;
ALTER TABLE SUPPLIERS DROP CONSTRAINT SUPP_FK_2;
ALTER TABLE DRUG DROP CONSTRAINT DRG_FK_1;
ALTER TABLE DRUG DROP CONSTRAINT DRG_FK_2;
ALTER TABLE STOCK DROP CONSTRAINT STK_FK_1;
ALTER TABLE STOCK DROP CONSTRAINT STK_FK_2;
ALTER TABLE STOCK DROP CONSTRAINT STK_FK_3;

DROP TABLE PHARMACY;
DROP TABLE INVENTORY;
DROP TABLE DRUG_COMP;
DROP TABLE DRUG_SUPP;
DROP TABLE DRUG;
DROP TABLE SUPPLIERS;
DROP TABLE INCOME;
DROP TABLE OUTCOME;
DROP TABLE STOCK;

ALTER SESSION SET nls_language='ENGLISH';
ALTER SESSION SET nls_date_format='DD-MON-YYYY';

-- Tag: DC
CREATE TABLE DRUG_COMP 
    (DC_ID NUMBER(11) NOT NULL, 
    DC_NAME VARCHAR2(20) NOT NULL, 
    DC_ADDRESS VARCHAR2(100),
    CONSTRAINT DC_PK PRIMARY KEY(DC_ID) USING INDEX ENABLE);

-- Tag: DS
CREATE TABLE DRUG_SUPP
    (DS_ID NUMBER(11) NOT NULL,
    DS_NAME VARCHAR2(20) NOT NULL, 
    DS_ADDRESS VARCHAR2(100),
    CONSTRAINT DS_PK PRIMARY KEY(DS_ID) USING INDEX ENABLE);

-- Tag: PHA
CREATE TABLE PHARMACY
    (PHA_ID NUMBER(11) NOT NULL,
    PHA_NAME VARCHAR2(15),
    PHA_CONTACT VARCHAR2(16),
    PHA_ADDRESS VARCHAR2(100),
    CONSTRAINT PHA_PK PRIMARY KEY (PHA_ID) USING INDEX ENABLE);

-- Tag: IN
CREATE TABLE INCOME
    (IN_ID NUMBER(11) NOT NULL,
    CONSTRAINT IN_PK PRIMARY KEY (IN_ID) USING INDEX ENABLE);

-- Tag: OUT
CREATE TABLE OUTCOME
    (OUT_ID NUMBER(11) NOT NULL,
    CONSTRAINT OUT_PK PRIMARY KEY (OUT_ID) USING INDEX ENABLE);
    
    
-- Which contain foreign key

-- Tag: INV
CREATE TABLE INVENTORY
    (INV_ID NUMBER(11) NOT NULL,
    INV_AMOUNT NUMBER(13),
    INV_PHA_ID NUMBER(11) NOT NULL,
    CONSTRAINT INV_PK PRIMARY KEY (INV_ID) USING INDEX ENABLE);
    
-- Tag: DRG
CREATE TABLE DRUG
    (DRG_ID NUMBER(13,0) NOT NULL,
    DRG_NAME VARCHAR2(35) NOT NULL,
    DRG_TYPE VARCHAR2(15) NOT NULL,
    DRG_COMP_ID NUMBER(13,0) NOT NULL,
    DRG_STK_ID NUMBER(11) NOT NULL,
    DRG_EXPIRE DATE NOT NULL,
    CONSTRAINT DRG_PK PRIMARY KEY (DRG_ID) USING INDEX ENABLE);

-- Tag: SUPP
CREATE TABLE SUPPLIERS 
    (SUPP_ID NUMBER(11) NOT NULL, 
    SUPP_DS_ID NUMBER(11) NOT NULL,
    CONSTRAINT SUPP_PK PRIMARY KEY (SUPP_ID) USING INDEX ENABLE);

-- Tag: STK
CREATE TABLE STOCK
    (STK_ID NUMBER(11) NOT NULL,
    STK_BUYING_PRC NUMBER(6,2) NOT NULL,
    STK_SELLING_PRC NUMBER(6,2) NOT NULL,
    STK_IN_ID NUMBER(11) NOT NULL,
    STK_OUT_ID NUMBER(11) NOT NULL,
    STK_INV_ID NUMBER(11) NOT NULL,
    STK_INV_INDATE DATE NOT NULL,
    STK_INV_OUTDATE DATE NOT NULL,
    CONSTRAINT STK_PK PRIMARY KEY (STK_ID) USING INDEX ENABLE);
    
    
    
ALTER TABLE INVENTORY ADD CONSTRAINT INV_FK
    FOREIGN KEY (INV_PHA_ID) REFERENCES PHARMACY(PHA_ID);

ALTER TABLE DRUG ADD CONSTRAINT DRG_FK_1
    FOREIGN KEY (DRG_COMP_ID) REFERENCES DRUG_COMP(DC_ID);
    
ALTER TABLE DRUG ADD CONSTRAINT DRG_FK_2
    FOREIGN KEY (DRG_STK_ID) REFERENCES STOCK(STK_ID);
    
ALTER TABLE SUPPLIERS ADD CONSTRAINT SUPP_FK_1
    FOREIGN KEY (SUPP_DS_ID) REFERENCES DRUG_SUPP(DS_ID);

ALTER TABLE SUPPLIERS ADD CONSTRAINT SUPP_FK_2
    FOREIGN KEY (SUPP_DRG_ID) REFERENCES DRUG(DRG_ID);

ALTER TABLE STOCK ADD CONSTRAINT STK_FK_1
    FOREIGN KEY (STK_IN_ID) REFERENCES INCOME(IN_ID);

ALTER TABLE STOCK ADD CONSTRAINT STK_FK_2
    FOREIGN KEY (STK_OUT_ID) REFERENCES OUTCOME(OUT_ID);
    
ALTER TABLE STOCK ADD CONSTRAINT STK_FK_3
    FOREIGN KEY (STK_INV_ID) REFERENCES INVENTORY(INV_ID);
