INSERT INTO PATIENT VALUES
(1, 'GERALT', 'ORIVIA',
TO_DATE('24-MAY-1915', 'DD-MON-YYYY'),'Corvo Bianco/Toussaint');

INSERT INTO PATIENT VALUES
(2, 'JOHN', 'DOE',
TO_DATE('24-MAY-1915', 'DD-MON-YYYY'),'Manhattan/New York/United States');

INSERT INTO PATIENT VALUES
(3, 'BOJACK', 'HORSEMAN',
TO_DATE('02-JAN-1964', 'DD-MON-YYYY'),'Hollywoo/California/United States');

INSERT INTO PATIENT VALUES
(4, 'WALTER', 'WHITE',
TO_DATE('13-APR-1958', 'DD-MON-YYYY'),'Albuquerque/New Mexico/United States');

INSERT INTO PATIENT VALUES
(5, 'JESSE', 'PINKMAN',
TO_DATE('14-SEP-1984', 'DD-MON-YYYY'),'Alaska/United States');

INSERT INTO PATIENT VALUES
(6, 'DOGUKAN', 'GOK',
TO_DATE('25-JUN-1999', 'DD-MON-YYYY'),'BARIS MAH. 353.SK NO.94/2 BUCA/IZMIR');

INSERT INTO PATIENT VALUES
(7, 'SAID', 'ALIR',
TO_DATE('11-NOV-1993', 'DD-MON-YYYY'),'IZMIR/TURKEY');

INSERT INTO PATIENT VALUES
(8, 'CAGDAS BERKAY', 'VURKAN',
TO_DATE('30-AUG-1995', 'DD-MON-YYYY'),'IZMIR/TURKEY');

INSERT INTO PATIENT VALUES
(9, 'MERT', 'CALIS',
TO_DATE('25-JUN-1999', 'DD-MON-YYYY'),'IZMIR/TURKEY');

INSERT INTO PATIENT VALUES
(10, 'EFEKAN', 'GOK',
TO_DATE('23-OCT-2012', 'DD-MON-YYYY'),'BARIS MAH. 353.SK NO.94/2 BUCA/IZMIR');

INSERT INTO PATIENT VALUES
(11, 'JOHNNY', 'PETERS',
TO_DATE('05-APR-1997', 'DD-MON-YYYY'),'London/England');

INSERT INTO PATIENT VALUES
(12, 'OLIVER', 'MORRIS',
TO_DATE('05-FEB-1989', 'DD-MON-YYYY'),'London/England');

INSERT INTO PATIENT VALUES
(13, 'VLADIMIR', 'SEMYONOV',
TO_DATE('07-JUN-1976', 'DD-MON-YYYY'),'London/England');

INSERT INTO PATIENT VALUES
(14, 'EMILIANO RUBEN', 'GARCIA',
TO_DATE('03-AUG-1994', 'DD-MON-YYYY'),'Mexico City/Mexico');

INSERT INTO PATIENT VALUES
(15, 'BRENDAN', 'MOORE',
TO_DATE('07-JUL-1999', 'DD-MON-YYYY'),'Sydney/Australia');

INSERT INTO PATIENT VALUES
(16, 'FRANK', 'CASTLE',
TO_DATE('23-FEB-1974', 'DD-MON-YYYY'),'New York/United States');

INSERT INTO PATIENT VALUES
(17, 'BILLY', 'RUSSO',
TO_DATE('17-OCT-1976', 'DD-MON-YYYY'),'New York/United States');