drop table drug;

create table drug(
    DRG_ID NUMBER(13,0) NOT NULL,
    DRG_NAME VARCHAR2(35) NOT NULL,
    DRG_TYPE VARCHAR2(15) NOT NULL,
    DRG_COMP_ID NUMBER(13,0) NOT NULL,
    DRG_SUPPLIER_ID NUMBER(13,0) NOT NULL,
    DRG_SELLING_PRICE NUMBER(6,2) NOT NULL,
    DRG_BUYING_PRICE NUMBER(6,2) NULL ENABLE,
    DRG_GOV_SUPPORT NUMBER(2,2) NULL ENABLE,
    DRG_EXPIRE DATE NOT NULL,
    CONSTRAINT DRG_PK PRIMARY KEY (DRG_ID) USING INDEX ENABLE
);