DROP TABLE DRUG;
DROP TABLE PATIENT;
DROP TABLE EMPLOYEE;
DROP TABLE PHARMACY;
DROP TABLE INVENTORY;


CREATE TABLE DRUG
    (DRG_ID NUMBER(13,0) NOT NULL,
    DRG_NAME VARCHAR2(35) NOT NULL,
    DRG_TYPE VARCHAR2(15) NOT NULL,
    DRG_COMP_ID NUMBER(13,0) NOT NULL,
    DRG_SUPPLIER_ID NUMBER(13,0) NOT NULL,
    DRG_SELLING_PRICE NUMBER(6,2) NOT NULL,
    DRG_BUYING_PRICE NUMBER(6,2) NULL,
    DRG_GOV_SUPPORT NUMBER(2,2) NULL,
    DRG_EXPIRE DATE NOT NULL,
    CONSTRAINT DRG_PK PRIMARY KEY (DRG_ID) USING INDEX ENABLE);

CREATE TABLE PATIENT
    (PT_ID NUMBER(11),
    PT_NAME VARCHAR2(15),
    PT_SURNAME VARCHAR2(20),
    PT_BIRTHDATE DATE,
    PT_CONTACT VARCHAR2(100),
    CONSTRAINT emp_patientid_pk PRIMARY KEY (PT_ID) USING INDEX ENABLE);

CREATE TABLE EMPLOYEE
    (EMP_ID NUMBER(10),
    EMP_NAME VARCHAR2(15),
    EMP_SALARY NUMBER(5),
    EMP_CONTACT VARCHAR2(100),
    CONSTRAINT employee_empid_pk PRIMARY KEY (EMP_ID) USING INDEX ENABLE);

CREATE TABLE PHARMACY
    (PHA_ID NUMBER(11),
    PHA_CONTACT NUMBER(10),
    PHA_ADDRESS VARCHAR2(100),
    CONSTRAINT pharmacy_pharid_pk PRIMARY KEY (PHA_ID) USING INDEX ENABLE);

CREATE TABLE INVENTORY
    (INV_ID NUMBER(11),
    CONSTRAINT inventory_invid_pk PRIMARY KEY (INV_ID) USING INDEX ENABLE);
